site_name: Kings Choice s-1201 Wiki!
extra:
  meta:
    - name: robots
      content: noindex, nofollow
nav:
  - Main: index.md
  - Events Guides:
    - Chess: chess.md
    - Murder Mystery: mystery-murder.md
    - Royal Mines: royal-mines.md