site_name: Kings Choice s-1201 Wiki!
extra:
  meta:
    - name: robots
      content: noindex, nofollow
nav:
  - Main: index.md
  - Events Guides:
    - Chess: events/chess.md
    - Murder Mystery: events/mystery-murder.md
    - Royal Mines: events/royal-mines.md
    - Scarlet Beauty: events/scarlet-beauty.md
    - Twilight Castle: events/twilight-castle.md
# theme:
#   name: readthedocs
#   highlightjs: true
#   hljs_languages:
#     - yaml
#     - rust
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark side
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light side