site_name: Kings Choice s-1201 Wiki!
extra:
  meta:
    - name: robots
      content: noindex, nofollow
nav:
  - Main: index.md
  - Events Guides:
    - Chess: chess.md
    - Murder Mystery: mystery-murder.md
    - Royal Mines: royal-mines.md
    - Scarlet Beauty: scarlet-beauty.md
    - Twilight Castle: twilight-castle.md
    - War of Lions: war-of-lions.md
    - Masquerade Ball: masquerade-ball.md
# theme:
#   name: readthedocs
#   highlightjs: true
#   hljs_languages:
#     - yaml
#     - rust
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark side
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light side